// Build app/parking-db.js from Michael Fogleman's Rush Hour database (MIT,
// https://github.com/fogleman/rush — rush.txt.bz2, 2.58M puzzles). Reads the text on stdin:
//
//   bzcat rush.txt.bz2 | node tools/pick-parking.mjs > app/parking-db.js
//
// Each line is "moves board clusterSize". For every level we keep up to PER_LEVEL puzzles,
// spread evenly over the level's move counts (so a level isn't all its most common count),
// picked by a seeded reservoir sample so the output is the same every run.
import { createInterface } from 'node:readline';

const LEVELS = [
  { name: '입문', min: 2, max: 6 },
  { name: '초급', min: 7, max: 12 },
  { name: '중급', min: 13, max: 20 },
  { name: '고급', min: 21, max: 32 },
  { name: '마스터', min: 33, max: 60 },
];
const PER_LEVEL = 600;

let s = 20260927;
const rand = () => { s = (s * 1103515245 + 12345) >>> 0; return s / 4294967296; };

// reservoir per move count, sized so each level's counts share PER_LEVEL
const quota = {};
for (const L of LEVELS) {
  const n = L.max - L.min + 1;
  for (let m = L.min; m <= L.max; m++) quota[m] = Math.ceil(PER_LEVEL / n);
}
const seen = {}, keep = {};
const rl = createInterface({ input: process.stdin, crlfDelay: Infinity });
for await (const line of rl) {
  const [mv, board] = line.split(/\s+/);
  const m = Number(mv);
  if (!quota[m]) continue;
  seen[m] = (seen[m] ?? 0) + 1;
  const r = (keep[m] ??= []);
  if (r.length < quota[m]) r.push(board);
  else { const j = Math.floor(rand() * seen[m]); if (j < quota[m]) r[j] = board; }
}

// a level with few puzzles at its top counts lends the spare room to its lower ones: top up from
// counts that had more than their quota by taking every puzzle we kept (quota is already the cap)
const out = LEVELS.map((L) => {
  const list = [];
  for (let m = L.min; m <= L.max; m++) for (const b of keep[m] ?? []) list.push(`${m} ${b}`);
  return { ...L, puzzles: list };
});

console.log('// Generated by tools/pick-parking.mjs from Michael Fogleman\'s Rush Hour database');
console.log('// (MIT, https://github.com/fogleman/rush). Each entry: "<min moves> <36-char board>",');
console.log('// row-major, o empty, x wall, A the red car, B–Z the others. Do not edit by hand.');
console.log(`export const LEVELS = ${JSON.stringify(out.map(({ name, min, max }) => ({ name, min, max })))};`);
console.log('export const PUZZLES = [');
for (const L of out) console.log(`  ${JSON.stringify(L.puzzles)},`);
console.log('];');
console.error(out.map((L) => `${L.name} ${L.min}-${L.max}: ${L.puzzles.length}`).join(' | '));
